### ISSUE TITLE
FEWD_Week2Assignment_Relaxr

### ISSUE THREAD

**Issue by menaka1510** [menaka1510/FEWD_Week2#2]
Hi @wmyers Sorry about the late submission (was away on an unplanned trip). Here is the link to the FEWD week 2 (Relaxr landing page) assignment: https://github.com/menaka1510/FEWD_Week2/tree/master/in-class-excercises/assignment/submission

See you in class next week!

-- Menaka

**Comment by wmyers** [comment]
Hi Menaka

No worries. Looks good, see you on Sat
